# Generated by Django 5.1.6 on 2026-06-02 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='featured_image_static',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
