# Generated by hand to match models.BlogPost / models.BlogRedirect exactly.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_set_featured_image_static'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='seo_title',
            field=models.CharField(blank=True, help_text='Title tag shown in search results. Keep it under 60 characters; the site name is added automatically. Falls back to the post title.', max_length=70),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='structured_data',
            field=models.TextField(blank=True, help_text='Optional extra JSON-LD for this post (for example an FAQPage block), rendered verbatim in the page head. Must be valid JSON.'),
        ),
        migrations.CreateModel(
            name='BlogRedirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_slug', models.SlugField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirects', to='blog.blogpost')),
            ],
            options={
                'ordering': ['old_slug'],
            },
        ),
    ]
