"""
Django settings for dynamite_project project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (for local development)
# In production, Render's environment variables will override these.
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production
DEBUG = False

# Configure allowed hosts. For production, set ALLOWED_HOSTS as an environment variable.
# The default here is a comma-separated string without protocol prefixes.
ALLOWED_HOSTS = os.environ.get(
    "ALLOWED_HOSTS",
    "dynamitemanagement.com,www.dynamitemanagement.com,dynamite-webpage.onrender.com"
).split(",")


# Application definition

# Cloudinary is used for MEDIA storage in production so uploaded files (e.g. blog
# featured images) survive Render's ephemeral filesystem on every deploy.
# When CLOUDINARY_URL is unset we fall back to local-disk MEDIA for development.
USE_CLOUDINARY = bool(os.environ.get("CLOUDINARY_URL"))

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    "widget_tweaks",
    "django_htmx",
    "tinymce",
    "core",
    "blog",
    "staff_portal",
    "honeypot",
    "captcha",
]

if USE_CLOUDINARY:
    # We use Cloudinary for MEDIA only and WhiteNoise for static. The
    # "cloudinary" app provides config from CLOUDINARY_URL; that's all we need —
    # MediaCloudinaryStorage (wired via STORAGES below) works as a plain backend
    # class without app registration.
    #
    # We deliberately do NOT add the "cloudinary_storage" app to INSTALLED_APPS:
    # it overrides collectstatic with a static-on-Cloudinary variant that reads
    # the legacy settings.STATICFILES_STORAGE, which Django 5.1 removed — that
    # override crashed the build with AttributeError. Standard collectstatic plus
    # WhiteNoise is the correct path for our static files.
    INSTALLED_APPS.append("cloudinary")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Serve static files efficiently
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "dynamite_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "dynamite_project.wsgi.application"

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
    )
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Storage backends.
#
# Django 5.1 REMOVED the old STATICFILES_STORAGE and DEFAULT_FILE_STORAGE
# settings — they are now silently ignored, and the unified STORAGES dict below
# is the only thing Django reads. The previous config set DEFAULT_FILE_STORAGE
# to Cloudinary, which Django 5.1 dropped on the floor, so uploaded media kept
# landing on Render's ephemeral disk and vanished on every deploy. Define both
# backends through STORAGES so the Cloudinary wiring actually takes effect.
STORAGES = {
    "default": {
        # Local-disk uploads for development; overridden below for production.
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        # Whitenoise: compression + hashed filenames for long-lived caching.
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# When CLOUDINARY_URL is set (production on Render), store uploaded media in
# Cloudinary so featured images persist across deploys. Locally CLOUDINARY_URL
# is unset, so uploads continue to write to MEDIA_ROOT for normal development.
if USE_CLOUDINARY:
    STORAGES["default"]["BACKEND"] = "cloudinary_storage.storage.MediaCloudinaryStorage"
elif os.environ.get("RENDER"):
    # Running on Render without Cloudinary means media is written to the
    # ephemeral filesystem and wiped on the next deploy. Make that loud in the
    # deploy/runtime logs so this misconfiguration can never silently recur.
    import warnings

    warnings.warn(
        "CLOUDINARY_URL is not set on Render: uploaded media will be stored on "
        "the ephemeral filesystem and LOST on the next deploy. Set CLOUDINARY_URL "
        "in the Render environment to persist blog images.",
        RuntimeWarning,
    )

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# reCAPTCHA Settings
RECAPTCHA_SITE_KEY = os.environ.get('RECAPTCHA_SITE_KEY', '')
RECAPTCHA_SECRET_KEY = os.environ.get('RECAPTCHA_SECRET_KEY', '')

# Email Settings - Secure configuration using environment variables
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.sendgrid.net')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'info@hoafiscal.com')

# For development, if DEBUG is True, use console backend to see emails in the console
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    print("Using console email backend for development")

# Honeypot settings
HONEYPOT_FIELD_NAME = 'website'  # Field bots typically fill
HONEYPOT_VALUE = ''  # Must be empty
def honeypot_validator(value):
    """Check that the honeypot field is empty."""
    return not value

HONEYPOT_VERIFIER = honeypot_validator

# Authentication
LOGIN_URL = "/staff/login/"
LOGIN_REDIRECT_URL = "/staff/"
LOGOUT_REDIRECT_URL = "/"

# Anthropic API Key for Claude AI
ANTHROPIC_API_KEY = os.environ.get('BLOG_API_KEY', '')
PEXELS_API_KEY = os.environ.get('PEXELS_API_KEY', '')

# TinyMCE Configuration
TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": "file edit view insert format tools table help",
    "plugins": "advlist autolink lists link image charmap preview anchor "
               "searchreplace visualblocks code fullscreen "
               "insertdatetime media table code help wordcount",
    "toolbar": "undo redo | blocks | bold italic backcolor | "
               "alignleft aligncenter alignright alignjustify | "
               "bullist numlist outdent indent | removeformat | help",
    "content_css": "default",
}