# Generated by Django 6.1.1 on 2026-09-26 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Working title', max_length=200)),
                ('target_keyword', models.CharField(max_length=200)),
                ('secondary_keywords', models.TextField(blank=True, help_text='One per line')),
                ('state', models.CharField(blank=True, help_text='WA, FL, CA… blank = national', max_length=10)),
                ('is_law_post', models.BooleanField(default=True, help_text='Requires official statute/bill sources')),
                ('category_name', models.CharField(blank=True, max_length=100)),
                ('tags', models.CharField(blank=True, help_text='Comma separated', max_length=255)),
                ('angle', models.TextField(blank=True, help_text='What the post must say / editorial notes')),
                ('source_urls', models.TextField(blank=True, help_text='Official statute / bill / agency URLs, one per line')),
                ('refresh_slug', models.CharField(blank=True, help_text='Slug of an existing post to rewrite in place instead of creating a new one', max_length=200)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('drafting', 'Drafting'), ('drafted', 'Drafted'), ('approved', 'Approved'), ('published', 'Published'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('post_id', models.CharField(blank=True, max_length=64)),
                ('post_slug', models.CharField(blank=True, max_length=200)),
                ('draft_title', models.CharField(blank=True, max_length=200)),
                ('seo_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('meta_keywords', models.CharField(blank=True, max_length=255)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('faq', models.JSONField(blank=True, default=list)),
                ('cover_spec', models.JSONField(blank=True, default=dict)),
                ('cover', models.ImageField(blank=True, upload_to='pipeline/covers/')),
                ('cover_alt', models.CharField(blank=True, max_length=255)),
                ('verification_report', models.TextField(blank=True)),
                ('quotes_verified', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('tokens_used', models.PositiveIntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['publish_at', 'created'],
            },
        ),
        migrations.CreateModel(
            name='LawAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=4)),
                ('bill_id', models.CharField(max_length=40, unique=True)),
                ('bill_number', models.CharField(max_length=40)),
                ('title', models.TextField()),
                ('url', models.URLField(max_length=500)),
                ('last_action', models.CharField(blank=True, max_length=255)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('matched_query', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('briefed', 'Briefed'), ('ignored', 'Ignored')], default='new', max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('brief', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content_pipeline.contentbrief')),
            ],
            options={
                'ordering': ['-last_action_date', '-created'],
            },
        ),
        migrations.CreateModel(
            name='SearchSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('page', models.URLField(max_length=500)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('impressions', models.PositiveIntegerField(default=0)),
                ('ctr', models.FloatField(default=0)),
                ('position', models.FloatField(default=0)),
                ('top_query', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['-week_start', '-clicks'],
                'unique_together': {('week_start', 'page')},
            },
        ),
    ]
