# Generated by Django 6.1.1 on 2026-09-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbrief',
            name='cover_credit',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='cover_photo_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='cover_source_page',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='photo_queries',
            field=models.JSONField(blank=True, default=list, help_text='Stock-photo searches for the cover'),
        ),
        migrations.AddField(
            model_name='contentbrief',
            name='rejected_photo_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
