# Generated by Django 6.1.1 on 2026-09-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0002_photo_covers'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentbrief',
            name='source_text',
            field=models.TextField(blank=True, help_text='Official text fetched from source_urls (quotes are checked against this)'),
        ),
    ]
