# Generated by Django 5.1.10 on 2026-09-26 20:31

import content_pipeline.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0003_cowork_engine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentbrief',
            name='cover',
            field=models.ImageField(blank=True, storage=content_pipeline.models.cover_storage, upload_to='pipeline/covers/'),
        ),
    ]
