# Generated by Django 5.1.6 on 2026-09-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_pipeline', '0004_cover_storage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('form', models.CharField(help_text='contact, signup, register…', max_length=40)),
                ('channel', models.CharField(choices=[('search', 'Search engine'), ('ai', 'AI assistant'), ('paid', 'Paid ads'), ('our_sites', 'Our other sites'), ('referral', 'Other website'), ('direct', 'Direct / unknown')], default='direct', max_length=20)),
                ('landing_page', models.CharField(blank=True, help_text='First page of the visit', max_length=500)),
                ('referrer', models.CharField(blank=True, help_text='Where the visit came from', max_length=500)),
                ('form_page', models.CharField(blank=True, help_text='Page the form was sent from', max_length=500)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
